apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 1
  selector: 
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: web
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
       